using ArrowPointCANBusTool.Configuation;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ArrowPointCANBusTool.Configuration
{
    public class ConfigManager
    {

        public void LoadConfig(string filename)
        {

            // SchemaClass is the root class generated by Xsd2Code
            NetworkDefinition configuration = NetworkDefinition.LoadFromFile(filename);

            configuration.Document.company = "foo";

            configuration.SaveToFile(filename);

        }

    }
}
